import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../public/observer.js',import.meta.url),'utf8');
async function ui(post){
 const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{value:id==='#seconds'?'60':'2',disabled:false,textContent:'',innerHTML:'',style:{},hidden:true});return nodes.get(id);};
 const context={document:{querySelector:node,querySelectorAll:()=>[]},fetch:async(path,options)=>{let data;if(options)data=await post(path,JSON.parse(options.body));else data=path.endsWith('/runs')?{runs:[]}:{scan:null};return{ok:!data.error,json:async()=>data};},setTimeout,URL,Blob,console};
 vm.runInNewContext(source,context);await new Promise(r=>setImmediate(r));return node;
}
const scan={id:'scan1',completedAt:Date.now(),nextScanAt:Date.now()+120000,remaining:9,cached:true,candidates:[{mint:'a',name:'<script>bad</script>',group:'new'}],picks:[{mint:'a',group:'new',reason:'<img onerror=bad>'}],errors:[],selectionError:null,aiStartedAt:1,aiFinishedAt:4};
test('repeat scan displays cached results beside the button and escapes site/model text',async()=>{const n=await ui(async()=>scan);await n('#scan').onclick();assert.match(n('#scan-status').textContent,/Showing saved results/);assert.match(n('#selection').innerHTML,/&lt;script&gt;/);assert.ok(!n('#selection').innerHTML.includes('<img onerror'));assert.equal(n('#scan').disabled,false);});
test('empty selection never starts an automatic recording',async()=>{let calls=0;const n=await ui(async path=>{calls++;assert.equal(path,'/api/research/scan');return{...scan,picks:[],candidates:[]};});await n('#auto').onclick();assert.equal(calls,1);assert.match(n('#status').textContent,/Nothing recorded/);assert.equal(n('#auto').disabled,false);});
test('failed scan shows a nearby error and restores buttons',async()=>{const n=await ui(async()=>({error:'Browser unavailable'}));await n('#scan').onclick();assert.equal(n('#scan-status').textContent,'Browser unavailable');assert.equal(n('#scan').disabled,false);assert.equal(n('#auto').disabled,false);});
test('expired cached results cannot auto-start a recording',async()=>{let calls=0;const n=await ui(async()=>{calls++;return{...scan,completedAt:Date.now()-600000};});await n('#auto').onclick();assert.equal(calls,1);assert.match(n('#status').textContent,/too old/);});
test('auto watch passes the selected mint, provenance and assumptions to the recorder',async()=>{let observed;const n=await ui(async(path,body)=>{if(path.endsWith('/scan'))return scan;observed=body;return{id:'report1',frames:[],reviews:[],failure:'Interrupted',analysis:'No analysis'};});await n('#auto').onclick();assert.equal(observed.mint,'a');assert.equal(observed.scanId,'scan1');assert.equal(observed.seconds,60);assert.equal(n('#export').disabled,false);assert.equal(n('#image').hidden,true);});
